src/Microsoft.AspNet.Identity/IdentityUser.cs
test/Microsoft.AspNet.Identity.InMemory.Test/HttpSignInTest.cs
test/Microsoft.AspNet.Identity.InMemory.Test/InMemoryStoreTest.cs
test/Microsoft.AspNet.Identity.InMemory.Test/InMemoryUserStore.cs

InMemory test was the only one left using them, moved to a specific user
subclass which had them for that test project
Fixes https://github.com/aspnet/Identity/issues/310
cc @divega @suhasj

Remove navigation properties

---

test/Microsoft.AspNet.Identity.Test/IdentityOptionsTest.cs

`Configuration` is no longer an `IEnumerable`

React to Configuration API changes

---

src/Microsoft.AspNet.Identity/IdentityServiceCollectionExtensions.cs

@HaoK @Tratcher 
This code basically encapsulates the `AddWebEncoders` call and we don't have to do it explicitly in Identity. I verified all tests pass with this change.

Use configure from cookies repo

---

src/Microsoft.AspNet.Identity.EntityFramework/RoleStore.cs
src/Microsoft.AspNet.Identity.EntityFramework/UserStore.cs
src/Microsoft.AspNet.Identity/BuilderExtensions.cs
src/Microsoft.AspNet.Identity/DataProtectionTokenProvider.cs
src/Microsoft.AspNet.Identity/PasswordValidator.cs
src/Microsoft.AspNet.Identity/PhoneNumberTokenProvider.cs
src/Microsoft.AspNet.Identity/Rfc6238AuthenticationService.cs
src/Microsoft.AspNet.Identity/RoleManager.cs
src/Microsoft.AspNet.Identity/RoleValidator.cs
src/Microsoft.AspNet.Identity/TotpSecurityStampBasedTokenProvider.cs
src/Microsoft.AspNet.Identity/UserClaimsPrincipalFactory.cs
src/Microsoft.AspNet.Identity/UserValidator.cs
test/Microsoft.AspNet.Identity.InMemory.Test/InMemoryUserStore.cs

Using the "nameof" operator instead of magic string will help us if the variable change in the future for whatever the reason

Using 'nameof' operator instead of magic strings

---

test/Microsoft.AspNet.Identity.EntityFramework.InMemory.Test/project.json
test/Microsoft.AspNet.Identity.EntityFramework.Test/project.json

Fixing CI build. `System.Security.Claims` is incompatible with dnx451, which is the framework used by tests.
@anpete

Remove useless and incompatible dependencies

---

test/Microsoft.AspNet.Identity.EntityFramework.Test/CustomPocoTest.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/DbUtil.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/DefaultPocoTest.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/SqlStoreTestBase.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/UserStoreGuidKeyTest.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/UserStoreIntKeyTest.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/UserStoreStringKeyTest.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/UserStoreTest.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/Utilities/EntityFrameworkServiceBuilderExtension.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/Utilities/ScratchDatabaseFixture.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/Utilities/SqlServerTestStore.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/Utilities/TestEnvironment.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/config.json
test/Shared/UserManagerTestBase.cs

Use fixtures instead of test ordering to manage creation/deletion of scratch databases.
Fix #678 
cc @divega

Refactor EF tests database creation/deletion

---

src/Microsoft.AspNetCore.Identity/UserOptions.cs
test/Microsoft.AspNetCore.Identity.Test/IdentityOptionsTest.cs
test/Microsoft.AspNetCore.Identity.Test/UserValidatorTest.cs

Fixes https://github.com/aspnet/Identity/issues/742
cc @divega @blowdart

Add + to allowed username characters by default

---

src/Microsoft.AspNetCore.Identity/IdentityCookieOptions.cs

#763 
As part of fixing MusicStore tests in https://github.com/aspnet/MusicStore/pull/601, @natemcmaster found that we are not setting the cookie names correctly for cookies used by Identity. The reason for this is in the referenced issue. 
cc @Tratcher @HaoK

Redress cookie name

---

samples/IdentitySample.Mvc/Startup.cs
src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityDbContext.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/InMemoryContext.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/InMemoryEFUserStoreTest.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/RoleStoreTest.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/TestIdentityFactory.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/CustomPocoTest.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/DbUtil.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/DefaultPocoTest.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/UserStoreTest.cs

EF now has a parameterless constructor that can only be used when a derived context has OnConfiguring and is hence protected, and a constructor that takes a DbContextOptions.
@divega

Update IdentityDbContext constructors to reflect EF changes

---

samples/IdentitySample.Mvc/project.json
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/RoleStoreTest.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/TestIdentityFactory.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/DefaultPocoTest.cs

cc @ajcvickers 
This gets the repo to compile, but there's a bunch of failing tests that I don't know how to fix:
```C#
Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test.UserStoreGuidTest.CanFindRoleByNameWithManager [FAIL]
System.InvalidOperationException : No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions object in its constructor.
```

Reacting to EF changes

---

src/Microsoft.AspNet.Identity.AspNetCoreCompat/project.json

cc @HaoK  \ @divega 
Removing this makes patching our repos a bit easy. Since this package didn't ship with RTM, it seemed like an easier fix.

Remove Microsoft.AspNet.DataProtection.Extensions

---

src/Microsoft.AspNetCore.Identity/UserManager.cs

The current wording states the parameter is the normalized email address, which is not the case. This PR makes it explicit that the parameter can be any email, but the query will be based on the normalized value.

Clearing up FindByEmailAsync usage

---

test/Microsoft.AspNetCore.Identity.Test/SecurityStampValidatorTest.cs

Fixes CI failures caused by https://github.com/aspnet/Security/commit/fea5d5cfdc8fc9413ba7816cc108f4d893ac16e1
cc @anurse @Tratcher @divega @blowdart 
Since cookies clock is now seconds granulaurity, maybe we should change the corresponding SecurityStampValidationInterval to be total seconds instead of a Timespan which causes issues now

React to clock changes

---

test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.csproj
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test.csproj
test/Microsoft.AspNetCore.Identity.InMemory.Test/Microsoft.AspNetCore.Identity.InMemory.Test.csproj
test/Microsoft.AspNetCore.Identity.Test/Microsoft.AspNetCore.Identity.Test.csproj

- aspnet/Testing#248
- xUnit no longer supports .NET 4.5.1
- build tests for desktop .NET only on Windows

Bump test projects up to .NET 4.5.2

---

build/dependencies.props
samples/IdentitySample.Mvc/IdentitySample.Mvc.csproj
src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/Microsoft.AspNetCore.Identity.EntityFrameworkCore.csproj
src/Microsoft.AspNetCore.Identity.Specification.Tests/Microsoft.AspNetCore.Identity.Specification.Tests.csproj
src/Microsoft.AspNetCore.Identity/Microsoft.AspNetCore.Identity.csproj
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.csproj
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test.csproj
test/Microsoft.AspNetCore.Identity.InMemory.Test/Microsoft.AspNetCore.Identity.InMemory.Test.csproj
test/Microsoft.AspNetCore.Identity.Test/Microsoft.AspNetCore.Identity.Test.csproj

```
Microsoft.AspNet.Identity.AspNetCoreCompat.0.3.0-preview1-t00466eae3 -> net46
Microsoft.AspNetCore.Identity.2.0.0-preview1-t00466eae3 -> netcoreapp2.0
Microsoft.AspNetCore.Identity.EntityFrameworkCore.2.0.0-preview1-t00466eae3 -> netcoreapp2.0
Microsoft.AspNetCore.Identity.Specification.Tests.2.0.0-preview1-t00466eae3 -> netcoreapp2.0
```
`Microsoft.AspNet.Identity.AspNetCoreCompat` is for apps using pre-ASP.NET Core identity to be able to access ASP.NET Core Identity Databases.

netcoreapp2.0

---

src/Microsoft.AspNetCore.Identity.Service.IntegratedWebClient/IntegratedWebClientOpenIdConnectOptionsSetup.cs

This property was a leftover from auth 1.0 and isn't being used anymore and will be removed in https://github.com/aspnet/Security/pull/1206
There's a similar property on the AuthenticationScheme
@javiercn

Remove soon to be removed DisplayName set

---

src/Microsoft.AspNetCore.Identity/UserClaimsPrincipalFactory.cs

Fixes #1098. Allows derived types of `UserClaimsPrincipalFactory` to return their own `ClaimsPrincipal`s.
* Wasn't sure if I should make `CreatePrincipal` **`async`** or not. Thoughts? :thinking: :thought_balloon: 
Thanks again for your consideration,
Brian
:car: :blue_car: ***["Let the good times roll..."](https://www.youtube.com/watch?v=7BDBzgHXf64)***

Allow derived types of UserClaimsPrincipalFactory to return ClaimsPrincipals.

---

test/Microsoft.AspNetCore.Identity.Service.Test/ApplicationValidatorTest.cs

Skipping these two until we have time to fix them.
Reference #1266.

Skip failing tests

---

src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityDbContext.cs
src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityEntityFrameworkBuilderExtensions.cs
src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityUserContext.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/InMemoryContext.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/DefaultPocoTest.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/SqlStoreOnlyUsersTestBase.cs

Revert breaking changes to `IdentityDbContext<TUser>` which affected OnModelCreating, add a new IdentityUserContext base class to disambiguate (its the no role base context), and lets us leave IdentityDbContext untouched.
Merging since this broke MusicStore/SignalR chat
cc @ajcvickers

Revert IdentityDbContext breaking change

---

src/Microsoft.AspNetCore.Identity.Specification.Tests/UserManagerSpecificationTests.cs
src/Microsoft.Extensions.Identity.Core/IUserTwoFactorRecoveryCodeStore.cs
src/Microsoft.Extensions.Identity.Core/UserManager.cs
src/Microsoft.Extensions.Identity.Stores/UserStoreBase.cs
test/Microsoft.AspNetCore.Identity.InMemory.Test/InMemoryUserStore.cs

Add `CountRecoveryCodesAsync` API
Change default RecoveryCode generation to be the first 8 chars of a Guid()
cc @blowdart @ajcvickers

TFA tweaks for templates

---

src/Microsoft.AspNetCore.Identity.Specification.Tests/UserManagerSpecificationTests.cs
src/Microsoft.Extensions.Identity.Core/UserManager.cs

Fixes https://github.com/aspnet/Identity/issues/1388
@ajcvickers @blowdart

Fix regression with ChangePhoneNumber tokens

---

src/Microsoft.Extensions.Identity.Core/IdentityBuilder.cs
test/Microsoft.AspNetCore.Identity.InMemory.Test/FunctionalTest.cs
test/Microsoft.AspNetCore.Identity.Test/IdentityBuilderTest.cs

AddRoles should not be adding a store, that's done by the store
implementation, it should only be registering the role services.  Also
fixed the TUser/TRole generic parameters names since they were actually
the store types
Fixes https://github.com/aspnet/Identity/issues/1382
https://github.com/aspnet/Identity/issues/1379
@ajcvickers

Fix params name and AddRoles

---

src/Microsoft.AspNetCore.Identity/DataProtectionTokenProviderOptions.cs
src/Microsoft.AspNetCore.Identity/SecurityStampValidatorOptions.cs
src/Microsoft.Extensions.Identity.Core/ClaimsIdentityOptions.cs
src/Microsoft.Extensions.Identity.Core/LockoutOptions.cs
src/Microsoft.Extensions.Identity.Core/PasswordHasherOptions.cs
src/Microsoft.Extensions.Identity.Core/PasswordOptions.cs
src/Microsoft.Extensions.Identity.Core/SignInOptions.cs
src/Microsoft.Extensions.Identity.Core/UserOptions.cs

- Move defaults from remarks to summary for better intellisense.
- Add summary to describe LockoutOptions AllowedForNewUsers.
- Added defaults to xml docs where missing.
Fixes #1426

XML doc comments changes

---

src/Microsoft.Extensions.Identity.Core/IUserTwoFactorTokenProvider.cs

- Corrected typo: "heck" should be "check"

Corrected typo in IUserTwoFactorTokenProvider.cs

---

Directory.Build.props
NuGet.config
build/sources.props
src/Microsoft.AspNetCore.Identity.Service.Specification.Tests/NuGet.config

FYI - @javiercn 
I noticed this repo had a reference to dotnet-core in a custom nuget.config file. I removed this as we need conditionally set feeds via MSBuild, and need to use the dependencies.props file in aspnet/Universe to mirror an partner team dependencies.

Use MSBuild to set NuGet feeds instead of NuGet.config

---

src/Microsoft.AspNetCore.Diagnostics.Identity.Service/Microsoft.AspNetCore.Diagnostics.Identity.Service.csproj
src/Microsoft.AspNetCore.Identity.Service.Abstractions/Microsoft.AspNetCore.Identity.Service.Abstractions.csproj
src/Microsoft.AspNetCore.Identity.Service.AzureKeyVault/Microsoft.AspNetCore.Identity.Service.AzureKeyVault.csproj
src/Microsoft.AspNetCore.Identity.Service.Core/Microsoft.AspNetCore.Identity.Service.Core.csproj
src/Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore/Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore.csproj
src/Microsoft.AspNetCore.Identity.Service.IntegratedWebClient/Microsoft.AspNetCore.Identity.Service.IntegratedWebClient.csproj
src/Microsoft.AspNetCore.Identity.Service.Mvc/Microsoft.AspNetCore.Identity.Service.Mvc.csproj
src/Microsoft.AspNetCore.Identity.Service.Specification.Tests/Microsoft.AspNetCore.Identity.Service.Specification.Tests.csproj
src/Microsoft.AspNetCore.Identity.Service/Microsoft.AspNetCore.Identity.Service.csproj

Marking the following packages as IsPackable=false so they aren't produced or built by CI. This also causes them to be excluded from our cascading version analysis.
⚠️ this ONLY APPLIES to the 2.0.x branch. I won't merge this back to dev.
- Microsoft.AspNetCore.Diagnostics.Identity.Service
- Microsoft.AspNetCore.Identity.Service.Abstractions
- Microsoft.AspNetCore.Identity.Service.AzureKeyVault
- Microsoft.AspNetCore.Identity.Service.Core
- Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore
- Microsoft.AspNetCore.Identity.Service.IntegratedWebClient
- Microsoft.AspNetCore.Identity.Service.Mvc
- Microsoft.AspNetCore.Identity.Service.Specification.Tests
- Microsoft.AspNetCore.Identity.Service

Mark Identity service packages as IsPackable=false

---

src/Core/IUserRoleStore.cs

Fix some documentation inside `IUserRoleStore` that I recently noticed while working with it.

Fix IUserRoleStore docs

---

src/UI/IdentityDefaultUIConfigureOptions.cs

Respects the existing one if it's there.

[Fixes #1628] Avoid stomping on an existing FileProvider

---

test/Service.Core.Test/AuthorizationCodeExchangeIntegrationTest.cs
test/Service.Core.Test/DefaultSigningCredentialsSourceTest.cs
test/Service.Core.Test/JwtAccessTokenIssuerTest.cs
test/Service.Core.Test/JwtIdTokenIssuerTest.cs

These tests all fail intermittently due to #1630. Un-skip them when that issue is resolved.

Skip Flaky tests

---

src/Core/UserManager.cs

Fixes https://github.com/aspnet/Identity/issues/626
This doesn't really have any visible impact since we treated the security stamp as an opaque string anywyas.

Update new security stamp logic

---

src/UI/Areas/Identity/Pages/_ValidationScriptsPartial.cshtml

[Fixes #1730] Update IdentityUI's _ValidationScripts.cshtml to have the correct CDN urls for the scripts

Fix CDN urls to match the fallback source folders' versions

---

src/EF/IdentityUserContext.cs
src/Stores/IdentityUserToken.cs
src/UI/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml.cs
test/EF.Test/UserStoreEncryptPersonalDataTest.cs
test/Identity.FunctionalTests/ManagementTests.cs

We now display the linked login providers and the authenticator key if it exists.
Apps will be responsible for displaying any additional custom tokens they might store (like access/refresh tokens) since we don't have any way of enumerating these today.
@blowdart @ajcvickers

Include social logins and authenticator key as part of personal download

---

src/UI/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
src/UI/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
test/Identity.FunctionalTests/LoginTests.cs
test/Identity.FunctionalTests/RegistrationTests.cs
test/WebSites/Identity.DefaultUI.WebSite/Pages/Contoso/Login.cshtml.cs

Addresses #1762
While using the global authorization filter, `ConfirmEmail` is not accessible when clicking the verification email link (when logged out). So adding the attribute to it as well.

AllowAnonymous for external login providers and confirm email

---

src/UI/IdentityServiceCollectionUIExtensions.cs

The returns tag incorrectly states that AddDefaultIdentity<T>
returns IServiceCollection when it actually returns IdentityBuilder.

Fix /// comments

---

src/Stores/IdentityUserLogin.cs

Corrected a typo on the XML documentation of the UserId property that made it read "... sets the of the ..."

Fixed documentation typo

---

src/UI/Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/DeletePersonalData.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/Index.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/TwoFactorAuthentication.cshtml

* Some of the `ViewData["ActivePage"]` declarations were missing.
* `DeletePersonalData` and `DownloadPersonalData` should set `ActivePage` to `PersonalData` as there is no navigation element for `DeletePersonalData` or `DownloadPersonalData`.
* Remove `DeletePersonalData` and `DownloadPersonalData` variables and methods as they're no longer used by anthing.
* Make `PageNavClass` private as it is never used outside of its class.

Fix ActivePage declarations

---

test/Identity.FunctionalTests/Properties/AssemblyInfo.cs

For https://github.com/aspnet/Identity/issues/1926
Test running time go from 17s -> 29s locally
@Eilon @ajcvickers

Disable parallelization

---

src/Identity/SignInManager.cs
test/Identity.Test/SecurityStampValidatorTest.cs

Fixes https://github.com/aspnet/Identity/issues/1880
@ajcvickers @blowdart

Allow cookie validation when stores don't support security stamp

---

build/dependencies.props
src/Service.Specification.Tests/Microsoft.AspNetCore.Identity.Service.Specification.Tests.csproj
src/Specification.Tests/Microsoft.AspNetCore.Identity.Specification.Tests.csproj

Per xunit guidance, packages which deliver xunit bits shouldn't also depend on the xunit metapackage.
> https://xunit.github.io/releases/2.3:
> As a reminder: If you're extending xUnit.net and want to publish your extension as a NuGet package, you should import xunit.extensibility.core and/or xunit.extensibility.execution, not xunit or xunit.core. If you do this wrong, you might have problems generating your NuGet package via dotnet pack.

Change spec test packages to depend on xunit.execution.core, not the xunit metapackage

---

src/UI/Areas/Identity/Pages/V3/Account/Register.cshtml.cs
src/UI/Areas/Identity/Pages/V4/Account/Register.cshtml.cs

This pull-request fixes the logging category when messages are logged from the ASP.NET Identity UI Register page. Should be a non-breaking change.

Use the correct logging category inside RegisterModel

---

src/ApiAuth.IS/Microsoft.AspNetCore.ApiAuthorization.IdentityServer.csproj

This will prevent us from ending up with a "2.2.0" package when we do our final 2.2.0 RTM build, which would end up in build caches and drops.

Ensure ApiAuthorization.IdentityServer doesn't build a 2.2.0 package with the rest of RTM

---

samples/ApiAuthSample/Startup.cs

Remove `SetCompatibiltyVersion(...)` call in sample
