aspnet/Identity

test/Microsoft.AspNet.Identity.EntityFramework.Test/UserStoreTest.cs

Add attach tests for disconnected user/role

---

test/Shared/IdentityResultAssert.cs
test/Shared/TestFileLogger.cs
test/Shared/TestFileLoggerFactory.cs

@divega I had missed out on using file lock when reading from the file

Using file lock when reading file

---

samples/IdentitySample.Mvc/web.config

React to https://github.com/aspnet/Helios/pull/83

Change K_DETAILED_ERRORS to ASPNET_DETAILED_ERRORS

---

samples/IdentitySample.Mvc/Startup.cs
samples/IdentitySample.Mvc/project.json

Adding console logger to sample

---

src/Microsoft.AspNet.Identity/IdentityServiceCollectionExtensions.cs
src/Microsoft.AspNet.Identity/Properties/AssemblyInfo.cs
src/Microsoft.AspNet.Identity/RoleManager.cs
src/Microsoft.AspNet.Identity/UserManager.cs
test/Microsoft.AspNet.Identity.EntityFramework.InMemory.Test/RoleStoreTest.cs
test/Microsoft.AspNet.Identity.Test/IdentityBuilderTest.cs
test/Microsoft.AspNet.Identity.Test/RoleManagerTest.cs
test/Microsoft.AspNet.Identity.Test/RoleValidatorTest.cs
test/Microsoft.AspNet.Identity.Test/UserManagerTest.cs
test/Shared/MockHelpers.cs

- Remove constructor defaults
- Make service properties internal
- Add Logging/HttpContextAccessor services which are required by
identity
Fixes https://github.com/aspnet/Identity/issues/358
Fixes https://github.com/aspnet/Identity/issues/357
cc @divega @suhasj

API Review cleanup #1

---

src/Microsoft.AspNet.Identity/RoleManager.cs
src/Microsoft.AspNet.Identity/SignInManager.cs
src/Microsoft.AspNet.Identity/UserManager.cs
test/Microsoft.AspNet.Identity.Test/SignInManagerTest.cs
test/Shared/MockHelpers.cs

Busted for now see https://github.com/aspnet/Hosting/issues/180
cc @divega @suhasj

Move away from ILogger<>

---

build.cmd
build.sh
samples/IdentitySample.Mvc/Helios.cmd
samples/IdentitySample.Mvc/project.json
src/Microsoft.AspNet.Identity.EntityFramework/project.json
src/Microsoft.AspNet.Identity/UserValidator.cs
src/Microsoft.AspNet.Identity/project.json
test/Microsoft.AspNet.Identity.EntityFramework.InMemory.Test/project.json
test/Microsoft.AspNet.Identity.EntityFramework.Test/project.json
test/Microsoft.AspNet.Identity.InMemory.Test/project.json
test/Microsoft.AspNet.Identity.Test/project.json
test/Shared/UserManagerTestBase.cs

Prepping to be merged once ready.

Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

---

samples/IdentitySample.Mvc/Startup.cs
src/Microsoft.AspNet.Identity/IdentityServiceCollectionExtensions.cs
src/Microsoft.AspNet.Identity/project.json
test/Microsoft.AspNet.Identity.EntityFramework.Test/SqlStoreTestBase.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/UserStoreTest.cs
test/Microsoft.AspNet.Identity.Test/IdentityOptionsTest.cs

Remove IConfiguration from AddIdentity
Switch to referencing interface assemblies
cc @divega @suhasj

Cleanup AddIdentity and project.json

---

test/Microsoft.AspNet.Identity.EntityFramework.Test/CustomPocoTest.cs

@smitpatel @divega @HaoK 
Removed setting of int PK in the test code to a fixed value. Making it autogenerated. Should not affect the tests

Removed setting int PK

---

src/Microsoft.AspNet.Identity/UserManager.cs
test/Shared/UserManagerTestBase.cs

Rather than null ref boom...
Fixes https://github.com/aspnet/MusicStore/issues/477
cc @divega

No password = auto fail password checks

---

test/Microsoft.AspNet.Identity.Test/IdentityOptionsTest.cs

Fix build break due to Configuration rename

---

src/Microsoft.AspNet.Identity.EntityFramework/IdentityEntityFrameworkBuilderExtensions.cs

Makes AddEntityFrameworkStores use TryAdd instead of Add 

---

samples/IdentitySample.Mvc/project.json
src/Microsoft.AspNet.Identity.EntityFramework/project.json
test/Microsoft.AspNet.Identity.EntityFramework.InMemory.Test/project.json
test/Microsoft.AspNet.Identity.EntityFramework.Test/project.json

This reverts commit 769eb9f08bf20f05ee732812a9398ebf81bd6702.

Revert "React to aspnet/EntityFramework#2613"

---

src/Microsoft.AspNet.Identity/UserManager.cs

Fixes https://github.com/aspnet/Identity/issues/557
cc @divega

Switch to protected constants for token purposes

---

samples/IdentitySample.Mvc/project.json
src/Microsoft.AspNet.Identity.EntityFramework/project.json
test/Microsoft.AspNet.Identity.EntityFramework.Test/project.json

:watch: https://github.com/aspnet/EntityFramework/pull/3331

React to EF rename

---

samples/IdentitySample.Mvc/Scripts/jquery.validate-vsdoc.js
src/Microsoft.AspNet.Identity/Resources.resx

To correct word spell

---

samples/IdentitySample.Mvc/project.json

/cc @HaoK 
I don't think we need Microsoft.AspNet.Server.IIS anymore.

Modify project.json of sample

---

src/Microsoft.AspNet.Identity/IdentityServiceCollectionExtensions.cs

Fix functional unit test after hosting changes

---

test/Shared/MockHelpers.cs

Reacting to https://github.com/aspnet/Logging/pull/314.
Need to test locally.

Reacting to verbose rename

---

test/Microsoft.AspNet.Identity.EntityFramework.Test/CustomPocoTest.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/DefaultPocoTest.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/UserStoreGuidKeyTest.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/UserStoreIntKeyTest.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/UserStoreStringKeyTest.cs
test/Microsoft.AspNet.Identity.EntityFramework.Test/UserStoreTest.cs

Increase connection timeout for Sql Server tests

---

global.json
samples/IdentitySample.Mvc/Startup.cs
samples/IdentitySample.Mvc/hosting.json
samples/IdentitySample.Mvc/project.json
test/Microsoft.AspNet.Identity.InMemory.Test/FunctionalTest.cs

Reacting to https://github.com/aspnet/Hosting/pull/521

Reacting to new Hosting API

---

samples/IdentitySample.Mvc/Startup.cs
src/Microsoft.AspNet.Identity/IdentityBuilder.cs
src/Microsoft.AspNet.Identity/IdentityCookieOptions.cs
src/Microsoft.AspNet.Identity/IdentityOptions.cs
src/Microsoft.AspNet.Identity/IdentityServiceCollectionExtensions.cs
src/Microsoft.AspNet.Identity/SecurityStampValidator.cs
src/Microsoft.AspNet.Identity/SignInManager.cs
src/Microsoft.AspNet.Identity/UserClaimsPrincipalFactory.cs
src/Microsoft.AspNet.Identity/UserManager.cs
test/Microsoft.AspNet.Identity.Test/ApiConsistencyTest.cs
test/Microsoft.AspNet.Identity.Test/IdentityBuilderTest.cs
test/Microsoft.AspNet.Identity.Test/IdentityOptionsTest.cs
test/Microsoft.AspNet.Identity.Test/SecurityStampValidatorTest.cs
test/Microsoft.AspNet.Identity.Test/SignInManagerTest.cs
test/Microsoft.AspNet.Identity.Test/UserClaimsPrincipalFactoryTest.cs
test/Shared/MockHelpers.cs
test/Shared/UserManagerTestBase.cs

https://github.com/aspnet/Options/issues/105

Updating to new options pattern

---

test/Shared/TestLogger.cs

https://github.com/aspnet/Logging/issues/331

React to Logging API changes

---

samples/IdentitySample.Mvc/Startup.cs
src/Microsoft.AspNetCore.Identity/IdentityCookieOptions.cs
test/Microsoft.AspNetCore.Identity.Test/SignInManagerTest.cs

cc @divega @Tratcher 
Fixes https://github.com/aspnet/Identity/issues/744

Remove redundant setters for CookieAuthSchemes

---

samples/Interop45/Views/Manage/Index.cshtml

Fix Security Advisory 3137909 update

---

src/Microsoft.AspNetCore.Identity/IdentityCookieOptions.cs

Update cookie name

---

README.md
src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/project.json
src/Microsoft.AspNetCore.Identity/project.json

Fix package metadata

---

samples/IdentitySample.Mvc/Controllers/AccountController.cs
samples/IdentitySample.Mvc/Controllers/ManageController.cs

Reacting to Mvc changes

---

samples/IdentitySample.Mvc/Startup.cs
samples/IdentitySample.Mvc/project.json
samples/IdentitySample.Mvc/web.config
samples/IdentitySample.Mvc/wwwroot/web.config

Review: @Tratcher 
RC2 Approval: @Eilon @DamianEdwards

Move web.config and use ANCM

---

samples/IdentitySample.Mvc/project.json
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/project.json
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/project.json
test/Microsoft.AspNetCore.Identity.InMemory.Test/project.json
test/Microsoft.AspNetCore.Identity.Test/project.json

Migrate tests/samples/tools to portable

---

samples/IdentitySample.Mvc/project.json
samples/IdentitySample.Mvc/web.config

Update web.config and add publish tool

---

src/Microsoft.AspNetCore.Identity/DataProtectionTokenProvider.cs
test/Microsoft.AspNetCore.Identity.Test/UserManagerTest.cs
test/Shared/UserManagerTestBase.cs

@divega Fixes https://github.com/aspnet/Identity/issues/839

Remove vestiges of NotifyAsync

---

src/Microsoft.AspNetCore.Identity/IdentityCookieOptions.cs
src/Microsoft.AspNetCore.Identity/SignInManager.cs
test/Microsoft.AspNetCore.Identity.Test/IdentityOptionsTest.cs
test/Microsoft.AspNetCore.Identity.Test/SignInManagerTest.cs

Fixes https://github.com/aspnet/Identity/issues/848
cc @divega @blowdart

AutomaticAuthenticate = false for non ApplicationCookies

---

Identity.sln
samples/Interop4.5/Interop4.5.csproj

Remove interop sample from sln since it uses non public pkgs

---

README.md

This is particularly helpful to see most of the store providers in one place and it would be easy for newcomers to see that they are not tied to implementations provided by this repo.

list community maintained store providers on Readme

---

src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/RoleStore.cs
src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/UserStore.cs
src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/project.json
src/Microsoft.AspNetCore.Identity/SignInManager.cs
src/Microsoft.AspNetCore.Identity/project.json

Instead of Task.FromResult(0)
@pranavkm

Use TaskCache class from Microsoft.Extensions.TaskCache.Sources

---

src/Microsoft.AspNetCore.Identity/TokenProviderDescriptor.cs
src/Microsoft.AspNetCore.Identity/UserManager.cs
test/Microsoft.AspNetCore.Identity.Test/UserManagerTest.cs

Fixes https://github.com/aspnet/Identity/issues/859
cc @blowdart @divega

Add ProviderInstance for use in 2FA TokenProvider

---

src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/UserStore.cs
test/Shared/UserManagerTestBase.cs

Fixes https://github.com/aspnet/Identity/issues/975
@divega

EF: Switch to Find where possible

---

src/Microsoft.AspNet.Identity.AspNetCoreCompat/project.json

Add period to project.json description.

---

src/Microsoft.AspNetCore.Identity/IdentityErrorDescriber.cs
src/Microsoft.AspNetCore.Identity/PasswordOptions.cs
src/Microsoft.AspNetCore.Identity/PasswordValidator.cs
src/Microsoft.AspNetCore.Identity/Properties/Resources.Designer.cs
src/Microsoft.AspNetCore.Identity/Resources.resx
test/Microsoft.AspNetCore.Identity.Test/IdentityOptionsTest.cs
test/Microsoft.AspNetCore.Identity.Test/PasswordValidatorTest.cs

Fixes #1097 
Took the liberty to create a branch here. Feel free to delete if the issue is not accepted, no bad feelings ;)

Implementing PasswordOptions.RequiredUniqueChars

---

src/Microsoft.AspNetCore.Identity.Specification.Tests/IdentitySpecificationTestBase.cs
src/Microsoft.AspNetCore.Identity.Specification.Tests/Microsoft.AspNetCore.Identity.Specification.Tests.csproj

Reacting to https://github.com/aspnet/Testing/commit/a31400b7377909f5f8ae9f9496a0a8ffb0496a6f.

Bump Microsoft.AspNetCore.Identity.Specification.Tests to net452

---

build/dependencies.props
samples/IdentitySample.Mvc/IdentitySample.Mvc.csproj
src/Microsoft.AspNet.Identity.AspNetCoreCompat/Microsoft.AspNet.Identity.AspNetCoreCompat.csproj
src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/Microsoft.AspNetCore.Identity.EntityFrameworkCore.csproj
src/Microsoft.AspNetCore.Identity.Specification.Tests/Microsoft.AspNetCore.Identity.Specification.Tests.csproj
src/Microsoft.AspNetCore.Identity/Microsoft.AspNetCore.Identity.csproj
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.csproj
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test.csproj
test/Microsoft.AspNetCore.Identity.InMemory.Test/Microsoft.AspNetCore.Identity.InMemory.Test.csproj
test/Microsoft.AspNetCore.Identity.Test/Microsoft.AspNetCore.Identity.Test.csproj
test/Microsoft.AspNetCore.Identity.Test/SecurityStampValidatorTest.cs
test/Microsoft.AspNetCore.Identity.Test/SignInManagerTest.cs
test/Microsoft.AspNetCore.Identity.Test/UserManagerTest.cs

Upgrade to stable version of Moq
Simplify sample dependencies by using metapackage

Unify dependency versions to one file and remove workarounds

---

src/Microsoft.AspNetCore.Identity/UpperInvariantLookupNormalizer.cs

https://github.com/aspnet/Identity/issues/1149#issuecomment-290142263
Can bring it back once we are on 2.0
cc @ajcvickers @natemcmaster @pranavkm

Remove call to Normlize() for now

---

samples/IdentitySample.Mvc/IdentitySample.Mvc.csproj
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.csproj
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test.csproj
test/Microsoft.AspNetCore.Identity.InMemory.Test/Microsoft.AspNetCore.Identity.InMemory.Test.csproj
test/Microsoft.AspNetCore.Identity.Test/Microsoft.AspNetCore.Identity.Test.csproj

This reverts commit 36184161fbb80176f18d2479a27ad666b3182a0d.
Fixes #1141

Revert "Adding System.Security.Claims to samples and tests"

---

samples/IdentitySample.Mvc/Startup.cs
src/Microsoft.AspNetCore.Identity/BuilderExtensions.cs

@ajcvickers @Tratcher 
Less breaky for existing apps

UseIdentity => UseAuthentication

---

build/dependencies.props
src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/Microsoft.AspNetCore.Identity.EntityFrameworkCore.csproj
src/Microsoft.AspNetCore.Identity.Specification.Tests/Microsoft.AspNetCore.Identity.Specification.Tests.csproj
src/Microsoft.AspNetCore.Identity/Microsoft.AspNetCore.Identity.csproj

https://github.com/aspnet/Coherence/issues/175

Remove unnecessary package references

---

build/dependencies.props
src/Microsoft.AspNetCore.Identity.Service.Specification.Tests/Microsoft.AspNetCore.Identity.Service.Specification.Tests.csproj
src/Microsoft.AspNetCore.Identity.Specification.Tests/IdentitySpecificationTestBase.cs
src/Microsoft.AspNetCore.Identity.Specification.Tests/Microsoft.AspNetCore.Identity.Specification.Tests.csproj
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.csproj
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test.csproj
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/UserStoreTest.cs
test/Microsoft.AspNetCore.Identity.InMemory.Test/Microsoft.AspNetCore.Identity.InMemory.Test.csproj
test/Microsoft.AspNetCore.Identity.Service.Abstractions.Test/Microsoft.AspNetCore.Identity.Service.Abstractions.Test.csproj
test/Microsoft.AspNetCore.Identity.Service.Core.Test/AuthorizationCodeIssuerTest.cs
test/Microsoft.AspNetCore.Identity.Service.Core.Test/AuthorizeIntegrationTest.cs
test/Microsoft.AspNetCore.Identity.Service.Core.Test/Microsoft.AspNetCore.Identity.Service.Core.Test.csproj
test/Microsoft.AspNetCore.Identity.Service.Test/Microsoft.AspNetCore.Identity.Service.Test.csproj
test/Microsoft.AspNetCore.Identity.Test/Microsoft.AspNetCore.Identity.Test.csproj

Part of https://github.com/aspnet/Coherence-Signed/issues/497
Update to xunit 2.3 and vstest.console 15.3
Also, fixed issues that xunit.analyzers found.
FYI - @javiercn

Upgrade test framework versions and fix test issues

---

src/Microsoft.AspNetCore.Diagnostics.Identity.Service/DeveloperCertificateMiddleware.cs
src/Microsoft.AspNetCore.Identity.Service.Core/DeveloperCertificateSigningCredentialsSource.cs
src/Microsoft.AspNetCore.Identity.Service.Core/IdentityServiceBuilderExtensions.cs
src/Microsoft.AspNetCore.Identity.Service/IdentityServiceServiceCollectionExtensions.cs

make it no-op when environment != development and add a gesture to explicitly remove it

Include the developer certificate by default

---

test/Microsoft.AspNetCore.Identity.Service.Test/ApplicationValidatorTest.cs

Skip these tests in Preview2. Last one was accidentally against dev.

Skip failing tests

---

src/Microsoft.AspNetCore.Identity/SignInManager.cs

Does https://github.com/aspnet/Identity/issues/1274

Enlarged access to SignInOrTwoFactorAsync

---

src/Microsoft.AspNetCore.Diagnostics.Identity.Service/DeveloperCertificateMiddleware.cs

Remove usage of IOptionsCache

---

src/Microsoft.AspNetCore.Identity.Service/IdentityServiceServiceCollectionExtensions.cs
src/Microsoft.AspNetCore.Identity.Service/SessionManager.cs
src/Microsoft.AspNetCore.Identity/IdentityServiceCollectionExtensions.cs
test/Microsoft.AspNetCore.Identity.InMemory.Test/FunctionalTest.cs

CI is expected to fail until https://github.com/aspnet/Security/pull/1285 is merged.

React to API changes in CookieAuthenticationOptions

---

build/dependencies.props

As part of https://github.com/aspnet/Configuration/pull/686

Update Microsoft.Azure.KeyVault version

---

src/Microsoft.AspNetCore.Identity.Service/SessionManager.cs
src/Microsoft.AspNetCore.Identity/IdentityServiceCollectionExtensions.cs
test/Microsoft.AspNetCore.Identity.InMemory.Test/FunctionalTest.cs

CI is expected to fail until https://github.com/aspnet/Security/pull/1296 is available on feeds.

React to changes in CookieAuthenticationOptions

---

build/dependencies.props

https://github.com/aspnet/Configuration/issues/691

Update AzureKeyVaultVersion to 2.3.2

---

src/Microsoft.AspNetCore.Identity/BuilderExtensions.cs

Help to guide users upgrading to 2.0.

Fix the obsolete message on UseIdentity()

---

src/Microsoft.Extensions.Identity.Core/UserManager.cs

Fixes https://github.com/aspnet/Identity/issues/1325

Make token purpose consts public

---

src/Microsoft.Extensions.Identity.Core/RoleManager.cs
src/Microsoft.Extensions.Identity.Core/UserManager.cs

Validate/UpdateUser/Role are now protected
@ajcvickers 
Fixes https://github.com/aspnet/Identity/issues/1180 and https://github.com/aspnet/Identity/issues/1029

Expose some internal helpers

---

build/dependencies.props
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test.csproj
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/SqlStoreTestBase.cs
test/Microsoft.AspNetCore.Identity.Service.Core.Test/Microsoft.AspNetCore.Identity.Service.Core.Test.csproj
test/Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore.InMemory.Test/Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore.InMemory.Test.csproj
test/Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore.Test/Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore.Test.csproj
test/Microsoft.AspNetCore.Identity.Test/IdentityResultTest.cs
test/Microsoft.AspNetCore.Identity.Test/PasswordValidatorTest.cs
test/Microsoft.AspNetCore.Identity.Test/SignInManagerTest.cs
test/Microsoft.AspNetCore.Identity.Test/UserClaimsPrincipalFactoryTest.cs

Required a few minor changes due to xunit.analyzers.
cc @mikeharder @javiercn

Upgrade to xunit 2.3.0-beta4

---

src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityEntityFrameworkBuilderExtensions.cs
src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/Properties/Resources.Designer.cs
src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/Resources.resx
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/DefaultPocoTest.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/SqlStoreTestBase.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/UserStoreGuidKeyTest.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/UserStoreIntKeyTest.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/UserStoreStringKeyTest.cs

Fix for https://github.com/aspnet/Identity/issues/1373

[2.0.1] Allow use of base identity pocos

---

.gitignore
Directory.Build.targets
NuGet.config
build/common.props
build/dependencies.targets
src/Microsoft.AspNet.Identity.AspNetCoreCompat/Microsoft.AspNet.Identity.AspNetCoreCompat.csproj
version.props

CI will fail until we actually have a candidate build of the EF dependencies.
:watch: will wait until those are available to merge

[2.0.1] Update version.props and add list of dependendencies that are also being updated

---

src/Microsoft.Extensions.Identity.Core/UserManager.cs

This seems like it should be the other way around.

Fix ResetPasswordAsync documentation

---

src/Microsoft.AspNetCore.Identity.Service/IdentityServiceServiceCollectionExtensions.cs
src/Microsoft.AspNetCore.Identity.Specification.Tests/IdentitySpecificationTestBase.cs
src/Microsoft.AspNetCore.Identity.Specification.Tests/UserManagerSpecificationTests.cs
src/Microsoft.AspNetCore.Identity/IdentityServiceCollectionExtensions.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/InMemoryStoreWithGenericsTest.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test/TestIdentityFactory.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/DbUtil.cs
test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/SqlStoreTestBase.cs
test/Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore.Test/Utilities/DbUtil.cs
test/Microsoft.AspNetCore.Identity.Test/IdentityBuilderTest.cs
test/Microsoft.AspNetCore.Identity.Test/UserManagerTest.cs

From aspnet/HttpAbstractions#947 💄

Use AddHttpContextAccessor

---

samples/IdentitySample.Mvc/IdentitySample.Mvc.csproj
samples/IdentitySample.Mvc/Program.cs

so that it picks up the logging config from the `appsettings.json`

use WebHost.CreateDefaultBuilder in IdentitySample.Mvc

---

src/Microsoft.AspNetCore.Identity.Specification.Tests/UserManagerSpecificationTests.cs
src/Microsoft.Extensions.Identity.Core/TokenOptions.cs
src/Microsoft.Extensions.Identity.Core/UserManager.cs
test/Microsoft.AspNetCore.Identity.Test/IdentityOptionsTest.cs

- Added Quirk mode to control default provider
- Fixed new regression
- New tests (can use custom provider, quirk mode defaults)
Fixes: https://github.com/aspnet/Identity/issues/1483
@ajcvickers @blowdart @Eilon

Update fix to ChangePhoneNumber

---

README.md

There already is a RavenDB Provider listed in the repository description, I'd like to list my package https://github.com/maqduni/AspNetCore.Identity.RavenDb there as well, it's also the most downloaded and complete RavenDB provider.
Related issue https://github.com/aspnet/Identity/issues/1467

Add alternative RavenDB provider by maqduni.

---

src/Microsoft.AspNetCore.Identity.UI/IdentityDefaultUIConfigureOptions.cs

React to breaking change in MVC

---

samples/IdentitySample.DefaultUI/Startup.cs
samples/IdentitySample.Mvc/appsettings.json
src/Core/IdentityOptions.cs
src/Core/StoreOptions.cs
src/EF/IdentityUserContext.cs
test/EF.Test/DbUtil.cs
test/EF.Test/MaxKeyLengthSchemaTest.cs
test/EF.Test/SqlStoreOnlyUsersTestBase.cs
test/EF.Test/SqlStoreTestBase.cs

If set this will set max length of things we use for composite keys in
UserTokens/Logins
Needed for https://github.com/aspnet/templating/issues/62
@ajcvickers

Add Store.MaxLengthForKeys

---

samples/IdentitySample.DefaultUI/Data/Migrations/20171220235730_CreateIdentitySchema.Designer.cs
samples/IdentitySample.DefaultUI/Data/Migrations/20171220235730_CreateIdentitySchema.cs
samples/IdentitySample.DefaultUI/Data/Migrations/IdentityDbContextModelSnapshot.cs

Test run before template migration update, does this snapshot look like what you would expect now @ajcvickers ?
cc @javiercn

Update initial migration for DefaultUI sample

---

src/Microsoft.AspNet.Identity.AspNetCoreCompat/UserStore.cs
src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/RoleStore.cs
src/Microsoft.AspNetCore.Identity.Service.Core/CryptographyHelpers.cs
src/Microsoft.AspNetCore.Identity.Specification.Tests/UserManagerSpecificationTests.cs
src/Microsoft.AspNetCore.Identity/AspNetRoleManager.cs
src/Microsoft.AspNetCore.Identity/AspNetUserManager.cs
src/Microsoft.AspNetCore.Identity/IdentityConstants.cs
src/Microsoft.AspNetCore.Identity/SignInManager.cs
src/Microsoft.Extensions.Identity.Core/UserManager.cs

House Cleaning - Spell check and grammar. :shower:
:ear_of_rice: :stew: ***["Out here in the fields... I fight for my meals... It's only teenage wasteland..."](https://www.youtube.com/watch?v=IXWNSb4nUDY)***

House Cleaning - Spell check and grammar.

---

src/UI/Microsoft.AspNetCore.Identity.UI.csproj

Fixes https://github.com/aspnet/Identity/issues/1598

Exclude content files from package

---

samples/IdentitySample.DefaultUI/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
src/UI/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs

See https://github.com/aspnet/templating/pull/199
Identity code has moved to this repo from templating
cc @Eilon

Refresh user signin after updating their profile

---

version.props

BuildNumber on ExperimentalVersionSuffix

---

src/UI/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
src/UI/Areas/Identity/Pages/Account/Login.cshtml.cs
src/UI/Areas/Identity/Pages/Account/LoginWith2fa.cshtml.cs
src/UI/Areas/Identity/Pages/Account/LoginWithRecoveryCode.cshtml.cs
src/UI/Areas/Identity/Pages/Account/Logout.cshtml.cs
src/UI/Areas/Identity/Pages/Account/Register.cshtml.cs
src/UI/Areas/Identity/Pages/Error.cshtml.cs
test/Identity.FunctionalTests/AuthorizationTests.cs
test/Identity.FunctionalTests/Infrastructure/FunctionalTestsServiceCollectionExtensions.cs
test/Identity.FunctionalTests/LoginTests.cs
test/WebSites/Identity.DefaultUI.WebSite/Pages/Index.cshtml.cs

Add AllowAnonymous for some Identity razor pages

---

README.md

In response to @Elion comment in this discussion https://github.com/aspnet/Home/issues/2916#issuecomment-370019674

Add link to Identity.Firebase

---

src/Identity/IdentityConstants.cs
src/UI/Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml.cs
src/UI/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml.cs
src/UI/Areas/Identity/Pages/Account/Manage/ResetAuthenticator.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/ResetAuthenticator.cshtml.cs
src/UI/Areas/Identity/Pages/Account/Manage/SetPassword.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/SetPassword.cshtml.cs
src/UI/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
test/Identity.FunctionalTests/Infrastructure/FunctionalTestsServiceCollectionExtensions.cs
test/Identity.FunctionalTests/ManagementTests.cs
test/Identity.FunctionalTests/Pages/Account/Manage/ChangePassword.cs
test/Identity.FunctionalTests/Pages/Account/Manage/Index.cs
test/Identity.FunctionalTests/Pages/Account/Manage/LinkExternalLogin.cs
test/Identity.FunctionalTests/Pages/Account/Manage/ManageExternalLogin.cs
test/Identity.FunctionalTests/Pages/Account/Manage/RemoveExternalLogin.cs
test/Identity.FunctionalTests/Pages/Account/Manage/ResetAuthenticator.cs
test/Identity.FunctionalTests/Pages/Account/Manage/SetPassword.cs
test/Identity.FunctionalTests/Pages/Account/Manage/TwoFactorAuthentication.cs
test/Identity.FunctionalTests/Pages/Index.cs
test/Identity.FunctionalTests/UserStories.cs
test/WebSites/Identity.DefaultUI.WebSite/Pages/Contoso/Login.cshtml

Use RefreshSignInAsync

---

src/UI/Areas/Identity/Pages/Account/Manage/_Layout.cshtml
test/WebSites/Identity.DefaultUI.WebSite/Pages/_Layout.cshtml

Addresses https://github.com/aspnet/templating/issues/338

Use partial tag helper

---

src/Core/Properties/Resources.Designer.cs
src/Core/Resources.resx
src/Core/UserManager.cs
src/Specification.Tests/UserManagerSpecificationTests.cs

Fixes https://github.com/aspnet/Identity/issues/1669

Fix error message

---

src/UI/Areas/Identity/Pages/Account/ForgotPasswordConfirmation.cshtml.cs
src/UI/Areas/Identity/Pages/Account/Lockout.cshtml.cs
src/UI/Areas/Identity/Pages/Account/ResetPassword.cshtml.cs
src/UI/Areas/Identity/Pages/Account/ResetPasswordConfirmation.cshtml.cs
src/UI/Microsoft.AspNetCore.Identity.UI.csproj
test/Identity.FunctionalTests/Infrastructure/FunctionalTestsServiceCollectionExtensions.cs
test/Identity.FunctionalTests/LoginTests.cs
test/Identity.FunctionalTests/Pages/Account/Login.cs
test/Identity.FunctionalTests/UserStories.cs

Addresses #1736 and aspnet/templating#448

Add AllowAnonymous for resetting password navigation flow

---

build/dependencies.props
korebuild-lock.txt
test/WebSites/Identity.DefaultUI.WebSite/Identity.DefaultUI.WebSite.csproj

* Use Razor.Sdk package to not perform runtime compilation
* Use Mvc with PageResult fix (https://github.com/aspnet/Mvc/issues/7665)

Fix build break

---

src/UI/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
src/UI/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
test/Identity.FunctionalTests/LoginTests.cs
test/Identity.FunctionalTests/RegistrationTests.cs
test/WebSites/Identity.DefaultUI.WebSite/Pages/Contoso/Login.cshtml.cs

AllowAnonymous for external login providers and confirm email (#1769)

---

src/UI/IdentityServiceCollectionUIExtensions.cs

Fix namespace for AddDefaultIdentity

---

src/Core/IdentityBuilder.cs
src/Core/IdentityServiceCollectionExtensions.cs
src/Identity/IdentityServiceCollectionExtensions.cs
test/Identity.Test/IdentityBuilderTest.cs
test/Shared/MockHelpers.cs

Fixes https://github.com/aspnet/Identity/issues/1811
cc @davidfowl @ajcvickers

Don't hook cancellation tokens by default

---

src/Core/IdentityBuilder.cs
src/Identity/IdentityServiceCollectionExtensions.cs
test/Identity.Test/IdentityBuilderTest.cs
test/InMemory.Test/FunctionalTest.cs

Fixes https://github.com/aspnet/Identity/issues/1813
@ajcvickers

Fix issue with role claim missing in AddIdentityCore

---

src/UI/Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/DeletePersonalData.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/Index.cshtml
src/UI/Areas/Identity/Pages/Account/Manage/TwoFactorAuthentication.cshtml

@javiercn it looks like this didn't make it back into the 2.2 branch. Should it?

Merge release/2.1 to release/2.2

---

src/Core/TokenOptions.cs
src/UI/Areas/Identity/Pages/Account/Manage/EnableAuthenticator.cshtml.cs

Fixes https://github.com/aspnet/Identity/issues/1826

Allow QR AuthenticatorIssuer to be configurable

---

src/UI/Areas/Identity/Pages/Account/Login.cshtml.cs
test/Identity.FunctionalTests/LoginTests.cs
test/Identity.FunctionalTests/Pages/Account/Login.cs
test/Identity.FunctionalTests/UserStories.cs

Fix login.cshtml

---

src/UI/Areas/Identity/Pages/V3/Account/Login.cshtml.cs
src/UI/Areas/Identity/Pages/V4/Account/Login.cshtml.cs
test/Identity.FunctionalTests/LoginTests.cs
test/Identity.FunctionalTests/Pages/Account/Login.cs
test/Identity.FunctionalTests/UserStories.cs

Had to also make the change to the V3 page as well
@ajcvickers @blowdart @Eilon @javiercn

Merge 2.1 -> 2.2

---

src/UI/Areas/Identity/Pages/V3/_Layout.cshtml
test/Identity.Test/IdentityUIScriptsTest.cs

Fixes https://github.com/aspnet/Identity/issues/2053

Fixes integrity validation hashes for Identity UI V3
